# Change these first
owner: officialszcz # Your GitHub organization or username, where this repository lives
repo: statusik # The name of this repository

sites:
  - name: Strona Główna
    url: https://heyserve.pl/
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.heyserve.pl
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/attachments/1053749180574740600/1298967106527694868/heyserve.png?ex=671b7ce3&is=671a2b63&hm=e1378d3078bfe1e3f4b1022fe76c77781cc42aec862e757e031f8e16abacd470&
  name: Upptime
  introTitle: "Status **HeyServe**"
  introMessage: Tutaj możesz na bieżąco monitorować stan naszych usług oraz sprawdzać, czy występują jakiekolwiek przerwy w działaniu.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
